copyright = "© Your Name"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Berlin"
timeout = "120s"
title = "Gallery"

[params]
  defaultTheme = "dark"
  description = "Example site for hugo-theme-gallery"
  title = "My Gallery"
  [params.search]
    filter_taxonomies = false
    filter_years = false
    ignore_location = true
    index_all_pages = false
    max_results = 20
    threshold = 0.3
    expand_results_meta = true
    histories = false
  [params.author]
    email = "user@example.com"
    name = "Your Name"
  [params.socialIcons]
    facebook = "https://www.facebook.com/"
    instagram = "https://www.instagram.com/"
    github = "https://github.com/eskopp/hugo-gallery"
    youtube = "https://www.youtube.com/"
    email = "mailto:user@example.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  page = ["HTML"]
  section = ["HTML"]
  
[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"
  [[module.imports]]
    path = 'github.com/hugomods/search'

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/eskopp/hugo-gallery/"
    weight = 3

[services]
  [services.rss]
    limit = 100